services:
  demo-java:
    cpus: "0.25"
    mem_reservation: "1024M"
    mem_limit: "1024M"
    build: .
    ports:
      - "9000:8080"
    environment:
      - DB_URL=db:3306
      - DB_NAME=testdb
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - AWS_LAMBDA_FUNCTION_TIMEOUT=900
      - TZ=America/Sao_Paulo
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-volume:/var/lib/mysql/
volumes:
  db-volume: